apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newsapp
  template:
    metadata:
      labels:
        app: newsapp
    spec:
      containers:
      - name: newsapp
        image: udaykr7697/news-app:latest
        ports:
        - containerPort: 8080