apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
  namespace: vue-app-namespace  # Add the namespace here
  labels:
    app: vue-app
spec:
  selector:
    app: vue-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
