apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 80  # Container port
  type: LoadBalancer  # This will create an external IP (for cloud) or NodePort for local cluster
