name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify Node.js version

    - name: Install dependencies
      run: npm install  # Install npm dependencies

    - name: Build application
      run: npm run build  # Build the Vue application

    - name: Build Docker image
      run: |
        docker build -t udaykumar7697/vue-app:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a secret

    - name: Push Docker image
      run: |
        docker push udaykumar7697/vue-app:latest  # Replace with your Docker Hub username
